### ISSUE TITLE
HTML-Tags im Spec-Entwurf zu sehen, Beispiele nicht richtig gerendert

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/oer-service-card#6]
Siehe z.B. direkt am Anfang von https://dini-ag-kim.github.io/oer-service-card/draft/: `<section id="abstract">` Oder später unter https://dini-ag-kim.github.io/oer-service-card/draft/#sameas. Auch werden die JSON-Beispiele nicht richtig gerendert.

@sebastian-meyer, weißt du, was da los ist? Ich konnte da auf die Schnelle nichts finden.

**Comment by sebastian-meyer** [comment]
Offenbar wird das HTML nicht mehr korrekt erkannt, weshalb einige verpflichtende Abschnitte "fehlen" und auch der Import der Beispiele nicht mehr funktioniert. Ich habe ein Ticket für ReSpec aufgemacht: https://github.com/w3c/respec/issues/2850
